title: Illinois Shuffleboard Association
email: contact@illinoisshuffleboard.org
description: >-
  Welcome to The Illinois Shuffleboard Association website!
baseurl: ""
url: "https://illinoisshuffleboard.org"
twitter_username: IllinoisShuffle
github_username:  IllinoisShuffle
facebook_username: IllinoisShuffle
instagram_username: IllinoisShuffle

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
