backend:
  name: git-gateway
  branch: main

media_folder: "static/img/posts"
public_folder: "/img/posts"

collections:
  - name: "posts"
    label: "News Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "toml-frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Expiry Date", name: "expiryDate", widget: "datetime", format: "YYYY-MM-DD", required: false, hint: "Post will be hidden after this date" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
