name: Rebuild Site

on:
  schedule:
    - cron: '5 6 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    env:
      TRIGGER_ID: ${{ secrets.NETLIFY_TRIGGER_ID}}
    steps:
      - name: Curl request
        run: curl -X POST -d "trigger_branch=main&trigger_title=Triggered+by+GitHub+Actions&clear_cache=true" "https://api.netlify.com/build_hooks/$TRIGGER_ID"
